In [8]:
import pandas as pd
import numpy as np

In [2]:
with open("srr2prot.txt", 'r') as f:
    lsq = list(map(lambda x: x.strip('\n').split('\t'), f.readlines()))
dct = dict()
for element in lsq:
    dct[element[0]] = (element[1], element[2])
with open("fastqdump_log.txt", 'r') as f:
    ls = list(map(lambda x: x.rstrip('\n').lstrip("Written ").split(" spots for "), f.readlines()))
lsa = dict(map(lambda x: [x[1], int(x[0])], ls))
dct2 = {x : 0 for x in dct.keys()}
for key in list(dct.keys()):
    start, end = int(dct[key][0].strip("SRR")), int(dct[key][1].strip("SRR"))
    for i in range(start, end + 1):
        dct2[key] += lsa["SRR" + str(i)]

rds = dct2
print(rds.keys())

dict_keys(['input', 'adar', 'cbp', 'cbx3', 'chd1', 'chd4', 'chd7', 'ctcf', 'dnmt1', 'ezh2', 'hdac1', 'hnrnph', 'hnrnpu', 'hur', 'imp1', 'lsd1', 'nup98', 'pabp', 'pcaf', 'pcbx', 'phf8', 'rbbp5', 'stag2', 'suz12', 'wdr5'])

In [4]:
replicas = [9, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 
           3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3]
repls = {x: y for x, y in zip(list(rds.keys()), replicas)}

In [5]:
for key in rds.keys():
    rds[key] = rds[key], repls[key], dct[key][0], dct[key][1]

In [6]:
metadata = pd.DataFrame(rds).transpose().rename(columns={0:"reads_mln", 1:"replicas", 2: "start", 3:"end"})
metadata["prot"] = metadata.index
metadata

        reads_mln replicas       start         end    prot
input   451338296        9  SRR1976797  SRR1976850   input
adar     74702797        3  SRR1976598  SRR1976619    adar
cbp      95474992        3  SRR1976620  SRR1976625     cbp
cbx3     90498350        3  SRR1976626  SRR1976631    cbx3
chd1     91212989        3  SRR1976632  SRR1976643    chd1
chd4     89724268        3  SRR1976644  SRR1976649    chd4
chd7     86436353        3  SRR1976650  SRR1976655    chd7
ctcf     84800548        3  SRR1976656  SRR1976678    ctcf
dnmt1   178588164        3  SRR1976679  SRR1976708   dnmt1
ezh2     38370580        2  SRR1976709  SRR1976712    ezh2
hdac1   101519592        3  SRR1976713  SRR1976718   hdac1
hnrnph  122293531        3  SRR1976719  SRR1976751  hnrnph
hnrnpu  121668540        3  SRR1976752  SRR1976784  hnrnpu
hur      93783806        3  SRR1976785  SRR1976790     hur
imp1    118510251        3  SRR1976791  SRR1976796    imp1
lsd1     91437721        3  SRR1976851  SRR1976856    lsd1
nup98    52595461        3  SRR1976857  SRR1976862   nup98
pabp     90394101        3  SRR1976863  SRR1976868    pabp
pcaf    134082244        3  SRR1976869  SRR1976880    pcaf
pcbx     85344603        3  SRR1976881  SRR1976886    pcbx
phf8     56048984        3  SRR1976887  SRR1976892    phf8
rbbp5    82210565        3  SRR1976893  SRR1976904   rbbp5
stag2    55872636        2  SRR1976905  SRR1976908   stag2
suz12   160144084        3  SRR1976909  SRR1976937   suz12
wdr5     78171143        3  SRR1976938  SRR1976947    wdr5

In [7]:
fqc = pd.read_csv("multiqc_data/mqc_bowtie2_pe_plot_1.txt", sep='\t')
fqc = fqc.assign(Sample = lambda x: x.Sample.str.strip("mapped_reads | log_hisat_"))
fqc

,Sample,PE mapped uniquely,PE mapped discordantly uniquely,PE one mate mapped uniquely,PE multimapped,PE one mate multimapped,PE neither mate aligned
0,SRR1976598,3012353.0,40350.0,211575.0,257212.0,190532.5,287977.5
1,SRR1976599,3030564.0,37114.0,205739.0,259806.0,191440.5,275336.5
2,SRR1976600,2822634.0,36814.0,213814.5,238226.0,191478.5,304895.0
3,SRR1976601,3039003.0,39458.0,203069.5,260206.0,187653.5,270610.0
4,SRR1976602,3002185.0,28257.0,223689.0,259107.0,191321.5,295440.5
...,...,...,...,...,...,...,...
345,SRR1976943,7929281.0,64754.0,463754.0,674720.0,133726.0,1012282.0
346,SRR1976944,6199209.0,49580.0,346977.0,524432.0,101795.0,755907.0
347,SRR1976945,6185618.0,48752.0,351086.5,516764.0,102793.0,783347.5
348,SRR1976946,4653955.0,41018.0,196083.0,389198.0,64861.5,388905.5
349,SRR1976947,4935323.0,43314.0,218068.5,417135.0,70884.5,422667.0

In [9]:
align = {x: [] for x in metadata.prot}
for p in metadata.prot:
    start = dct[p][0]
    end = dct[p][1]
    tmp_df = fqc[(fqc.Sample >= start) & (fqc.Sample <= end)]
    align[p] = list(map(lambda x: round(sum(tmp_df[x])), tmp_df.columns[1:]))

In [10]:
aligning = pd.DataFrame(align).transpose().rename(columns={
    0:"PE mapped uniquely",
    1:"PE mapped discordantly uniquely",
    2:"PE one mate mapped uniquely",
    3:"PE multimapped",
    4:"PE one mate multimapped",
    5:"PE neither mate aligned"
})
aligning["prot"] = aligning.index

In [11]:
anot = pd.read_csv("annot_metrics.txt", sep=' ', header = None)
anot = anot.iloc[:, 1:3].rename(columns={1:"n_anot", 2:"SRR"}).assign(
    SRR = lambda x: x.SRR.str.lstrip("contacts/").str.rstrip(".bed"))
anot

       n_anot         SRR
0    17427331  SRR1976598
1    17482625  SRR1976599
2    16467659  SRR1976600
3    17512363  SRR1976601
4    17322258  SRR1976602
..        ...         ...
695  95018342  SRR1976943
696  74203410  SRR1976944
697  73862909  SRR1976945
698  50914821  SRR1976946
699  54258135  SRR1976947

[700 rows x 2 columns]

In [12]:
annot = {x: [] for x in metadata.prot}
for p in metadata.prot:
    start = dct[p][0]
    end = dct[p][1]
    tmp_df = anot[(anot.SRR >= start) & (anot.SRR <= end)]
    annot[p] = sum(tmp_df.n_anot)
annot

{'input': 8136271704,
 'adar': 488237195,
 'cbp': 2439631425,
 'cbx3': 1812958136,
 'chd1': 1882891561,
 'chd4': 3160005432,
 'chd7': 1722249031,
 'ctcf': 1807630685,
 'dnmt1': 5356156268,
 'ezh2': 997901021,
 'hdac1': 1631153048,
 'hnrnph': 1040239598,
 'hnrnpu': 1119930286,
 'hur': 1180919142,
 'imp1': 3586351246,
 'lsd1': 2705819133,
 'nup98': 1355759794,
 'pabp': 3770832086,
 'pcaf': 4473908030,
 'pcbx': 1860241823,
 'phf8': 817584252,
 'rbbp5': 1032853250,
 'stag2': 966895648,
 'suz12': 3533728138,
 'wdr5': 2127047374}

In [13]:
b = pd.merge(metadata, aligning)
b

,reads_mln,replicas,start,end,prot,PE mapped uniquely,PE mapped discordantly uniquely,PE one mate mapped uniquely,PE multimapped,PE one mate multimapped,PE neither mate aligned
0,451338296,9,SRR1976797,SRR1976850,input,358874374,2964591,16588428,34199770,8006014,30705118
1,74702797,3,SRR1976598,SRR1976619,adar,55792777,623055,4140781,4850601,3585258,5710324
2,95474992,3,SRR1976620,SRR1976625,cbp,78604846,717106,2621746,7852320,1107416,4571558
3,90498350,3,SRR1976626,SRR1976631,cbx3,74637645,614678,2894325,6209115,1218536,4924051
4,91212989,3,SRR1976632,SRR1976643,chd1,65863704,580248,3264486,11251511,1825688,8427352
5,89724268,3,SRR1976644,SRR1976649,chd4,71632288,590896,2211764,8722075,881903,5685342
6,86436353,3,SRR1976650,SRR1976655,chd7,72086170,624524,2189638,6742904,1030157,3762960
7,84800548,3,SRR1976656,SRR1976678,ctcf,66418707,412389,3749310,5961289,1430902,6827951
8,178588164,3,SRR1976679,SRR1976708,dnmt1,142875441,1007012,7658729,11309291,2087230,13650461
9,38370580,2,SRR1976709,SRR1976712,ezh2,30377536,272301,1312939,3181677,427200,2798927
10,101519592,3,SRR1976713,SRR1976718,hdac1,83525549,654845,3135026,7586691,1531402,5086079
11,122293531,3,SRR1976719,SRR1976751,hnrnph,98807909,769342,5496566,6533610,2358812,8327293
12,121668540,3,SRR1976752,SRR1976784,hnrnpu,98818257,748062,5140015,6689465,2300396,7972345
13,93783806,3,SRR1976785,SRR1976790,hur,78135527,812963,3536994,5132778,1596712,4568832
14,118510251,3,SRR1976791,SRR1976796,imp1,98801113,825142,3664561,7789026,1231530,6198880
15,91437721,3,SRR1976851,SRR1976856,lsd1,69349306,651680,2399224,12345696,1136458,5555358
16,52595461,3,SRR1976857,SRR1976862,nup98,38439781,279825,1776080,4780256,729642,6589877
17,90394101,3,SRR1976863,SRR1976868,pabp,72383491,599610,1859038,11570276,830438,3151248
18,134082244,3,SRR1976869,SRR1976880,pcaf,106544640,855566,5167018,9558315,1436134,10520571
19,85344603,3,SRR1976881,SRR1976886,pcbx,64882257,613576,2333456,10492340,1242858,5780116
20,56048984,3,SRR1976887,SRR1976892,phf8,45341501,329468,2468323,3422998,903239,3583455
21,82210565,3,SRR1976893,SRR1976904,rbbp5,63898023,594288,2968752,7177495,1569752,6002256
22,55872636,2,SRR1976905,SRR1976908,stag2,36152775,596139,1415925,10016492,987070,6704234
23,160144084,3,SRR1976909,SRR1976937,suz12,130772025,849547,6596690,8583897,2085112,11256814
24,78171143,3,SRR1976938,SRR1976947,wdr5,61538067,516560,3178824,5219312,967364,6751016

In [14]:
1 - b["PE neither mate aligned"] / b.reads_mln

0     0.931969
1     0.923559
2     0.952118
3      0.94559
4     0.907608
5     0.936635
6     0.956466
7     0.919482
8     0.923565
9     0.927055
10    0.949901
11    0.931907
12    0.934475
13    0.951283
14    0.947693
15    0.939244
16    0.874706
17    0.965139
18    0.921536
19    0.932273
20    0.936066
21    0.926989
22    0.880009
23    0.929708
24    0.913638
dtype: object

In [24]:
preannot = pd.read_csv("preannot_counts.txt", header = None, sep=" ").rename(columns={0: "n", 1:"SRR_id"})
annot = pd.read_csv("annot_counts.txt", header = None, sep=" ").rename(columns={0: "m", 1:"SRR_id"})
annot_stats = pd.merge(annot, preannot)

In [29]:
percent_annot = {}
for p in metadata.prot:
    start = dct[p][0]
    end = dct[p][1]
    tmp_df = annot_stats[(annot_stats.SRR_id >= start) & (annot_stats.SRR_id <= end)]
    percent_annot[p] = round(1/(sum(tmp_df.n)/sum(tmp_df.m)),3)
percent_annot

{'input': 0.878,
 'adar': 0.823,
 'cbp': 0.913,
 'cbx3': 0.897,
 'chd1': 0.882,
 'chd4': 0.92,
 'chd7': 0.888,
 'ctcf': 0.885,
 'dnmt1': 0.916,
 'ezh2': 0.916,
 'hdac1': 0.852,
 'hnrnph': 0.862,
 'hnrnpu': 0.84,
 'hur': 0.872,
 'imp1': 0.913,
 'lsd1': 0.91,
 'nup98': 0.91,
 'pabp': 0.928,
 'pcaf': 0.925,
 'pcbx': 0.884,
 'phf8': 0.884,
 'rbbp5': 0.88,
 'stag2': 0.835,
 'suz12': 0.912,
 'wdr5': 0.918}